//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fooditem
    {
        public int id { get; set; }
        public string name { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
